const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  minimize: () => ipcRenderer.invoke('window-minimize'),
  maximize: () => ipcRenderer.invoke('window-maximize'),
  close: () => ipcRenderer.invoke('window-close'),
  login: (u, p) => ipcRenderer.invoke('login', u, p),
  register: (u, p) => ipcRenderer.invoke('register', u, p),
  getProfile: () => ipcRenderer.invoke('get-profile'),
  logout: () => ipcRenderer.invoke('logout'),
  mcLogin: () => ipcRenderer.invoke('mc-login'),
  getMcAccount: () => ipcRenderer.invoke('get-mc-account'),
  mcLogout: () => ipcRenderer.invoke('mc-logout'),
  launchGame: (v) => ipcRenderer.invoke('launch-game', v),
  searchModrinth: (type, query) => ipcRenderer.invoke('search-modrinth', type, query),
  installModrinth: (slug, type) => ipcRenderer.invoke('install-modrinth', slug, type),
  installChibiMod: (slug, name, url) => ipcRenderer.invoke('install-chibi-mod', slug, name, url),
  getInstalledMods: () => ipcRenderer.invoke('get-installed-mods'),
  removeMod: (file) => ipcRenderer.invoke('remove-mod', file),
  getCosmetics: () => ipcRenderer.invoke('get-cosmetics'),
  getOwnedCosmetics: () => ipcRenderer.invoke('get-owned-cosmetics'),
  getEquippedCosmetics: () => ipcRenderer.invoke('get-equipped-cosmetics'),
  getCoins: () => ipcRenderer.invoke('get-coins'),
  buyCosmetic: (id) => ipcRenderer.invoke('buy-cosmetic', id),
  equipCosmetic: (id) => ipcRenderer.invoke('equip-cosmetic', id),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (s) => ipcRenderer.invoke('save-settings', s),
  onCoinsUpdated: (cb) => ipcRenderer.on('coins-updated', (_, d) => cb(d)),
  onLaunchError: (cb) => ipcRenderer.on('launch-error', (_, d) => cb(d)),
  onLaunchProgress: (cb) => ipcRenderer.on('launch-progress', (_, d) => cb(d)),
});
